In [2]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline



Load the test data set:

In [3]:
orgDS = pd.read_csv("../data/music_dataset_cleaned.csv")


In [4]:
orgDS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17996 entries, 0 to 17995
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0          17996 non-null  int64  
 1   Artist Name         17996 non-null  object 
 2   Track Name          17996 non-null  object 
 3   Popularity          17996 non-null  float64
 4   danceability        17996 non-null  float64
 5   energy              17996 non-null  float64
 6   key                 17996 non-null  float64
 7   loudness            17996 non-null  float64
 8   mode                17996 non-null  int64  
 9   speechiness         17996 non-null  float64
 10  acousticness        17996 non-null  float64
 11  instrumentalness    17996 non-null  float64
 12  liveness            17996 non-null  float64
 13  valence             17996 non-null  float64
 14  tempo               17996 non-null  float64
 15  duration_in min/ms  17996 non-null  float64
 16  time

In [5]:
orgDS = orgDS.drop('Unnamed: 0',1)

/tmp/ipykernel_18752/818387357.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  orgDS = orgDS.drop('Unnamed: 0',1)


Converting the class to string:

In [6]:
orgDS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17996 entries, 0 to 17995
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Artist Name         17996 non-null  object 
 1   Track Name          17996 non-null  object 
 2   Popularity          17996 non-null  float64
 3   danceability        17996 non-null  float64
 4   energy              17996 non-null  float64
 5   key                 17996 non-null  float64
 6   loudness            17996 non-null  float64
 7   mode                17996 non-null  int64  
 8   speechiness         17996 non-null  float64
 9   acousticness        17996 non-null  float64
 10  instrumentalness    17996 non-null  float64
 11  liveness            17996 non-null  float64
 12  valence             17996 non-null  float64
 13  tempo               17996 non-null  float64
 14  duration_in min/ms  17996 non-null  float64
 15  time_signature      17996 non-null  int64  
 16  Clas

In [7]:

# orgDS.Class = orgDS.Class.astype(str)


In [8]:
orgDS.head()

Artist Name                             Track Name  Popularity  \
0             Bruno Mars  That's What I Like (feat. Gucci Mane)        60.0   
1                 Boston                           Hitch a Ride        54.0   
2          The Raincoats                     No Side to Fall In        35.0   
3                   Deno             Lingo (feat. J.I & Chunkz)        66.0   
4  Red Hot Chili Peppers      Nobody Weird Like Me - Remastered        53.0   

   danceability  energy   key  loudness  mode  speechiness  acousticness  \
0         0.854   0.564   1.0    -4.964     1       0.0485      0.017100   
1         0.382   0.814   3.0    -7.230     1       0.0406      0.001100   
2         0.434   0.614   6.0    -8.334     1       0.0525      0.486000   
3         0.853   0.597  10.0    -6.528     0       0.0555      0.021200   
4         0.167   0.975   2.0    -4.279     1       0.2160      0.000169   

   instrumentalness  liveness  valence    tempo  duration_in min/ms  \
0          0.177562    0.0849   0.8990  134.071            234596.0   
1          0.004010    0.1010   0.5690  116.454            251733.0   
2          0.000196    0.3940   0.7870  147.681            109667.0   
3          0.177562    0.1220   0.5690  107.033            173968.0   
4          0.016100    0.1720   0.0918  199.060            229960.0   

   time_signature  Class  
0               4      5  
1               4     10  
2               4      6  
3               4      5  
4               4     10

In [9]:
# sns.boxenplot(data=DS,x="energy",y="key",hue="Class")

In [10]:
# sns.countplot(data=DS,x="key",hue="Class")

identify X and y

In [11]:
X = orgDS.iloc[:,2:-1].values
y = orgDS.iloc[:,-1].values

## Preporcisitng


In [12]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# X[:, 2] = le.fit_transform(X[:, 2])

In [13]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

## Spliting Dataset

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25,train_size=0.75, random_state = 42)

In [15]:

# X_train = trainDS.iloc[:,-7:-3].values
# y_train = trainDS.iloc[:,-1].values

# print(X_train,y_train)

In [16]:
# X_test = testDS.iloc[:,-7:-3].values
# y_test = testDS.iloc[:,-1].values

# print(X_test,y_test)

In [17]:

# spearmaner_cof, p_value = spearmanr(x,y)

# spearmaner_cof

In [18]:
# plt.scatter(x,y)

## preprocising

### test

In [19]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# X_test[:,2] = le.fit_transform(X_test[:,2])

In [20]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder

# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# X_test = np.array(ct.fit_transform(X_test))

### Train

In [21]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# X_train[:,2] = le.fit_transform(X_train[:,2])

In [22]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder

# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# X_train = np.array(ct.fit_transform(X_train))

In [23]:
# x = testDS.Class
# # x.reshape(-1, 1)

# y = testDS.tempo
# # y.reshape(-1, 1)

In [24]:
# type(x)

In [25]:
# log_reg.fit(x,y)

In [26]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 123)


In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [28]:
from sklearn.linear_model import LogisticRegression



logistic_regression = LogisticRegression()
logistic_regression.fit(X_train,y_train)



/home/ub/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
predictions = logistic_regression.predict(X_test)

In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.61      0.73      0.66       172
           1       0.00      0.00      0.00       340
           2       0.43      0.34      0.38       340
           3       0.73      0.60      0.66       104
           4       0.40      0.57      0.47        84
           5       0.64      0.63      0.64       340
           6       0.41      0.22      0.29       626
           7       0.89      0.93      0.91       134
           8       0.57      0.56      0.56       473
           9       0.46      0.43      0.44       663
          10       0.44      0.68      0.53      1223

    accuracy                           0.49      4499
   macro avg       0.51      0.52      0.50      4499
weighted avg       0.46      0.49      0.46      4499



/home/ub/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ub/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ub/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:


from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = logistic_regression.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)



[[125   0   0  12  20   0   0   7   0   6   2]
 [  0   0  12   0   0  22  52   0  18  40 196]
 [  0   0 116   0   0   6  25   0   8  44 141]
 [ 26   0   0  62   5   0   1   7   0   3   0]
 [ 19   0   0   2  48   0   0   2   0  13   0]
 [  0   0   9   0   0 215  17   0   2  63  34]
 [  0   0  35   0   0  31 140   0  34  89 297]
 [  7   0   0   3   0   0   0 124   0   0   0]
 [  0   0   0   0   0   0  23   0 263   3 184]
 [ 22   0  33   1  28  47  23   0   4 288 217]
 [  6   0  62   5  20  15  64   0 134  83 834]]


0.49233162925094465