In [1]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline



Load the test data set:

In [2]:
testDS = pd.read_csv("../data/music_dataset_test.csv")
trainDS = pd.read_csv("../data/music_dataset_train.csv")

In [3]:
testDS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5399 entries, 0 to 5398
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0.1        5399 non-null   int64  
 1   Unnamed: 0          5399 non-null   int64  
 2   Artist Name         5399 non-null   object 
 3   Track Name          5399 non-null   object 
 4   Popularity          5399 non-null   float64
 5   danceability        5399 non-null   float64
 6   energy              5399 non-null   float64
 7   key                 5399 non-null   float64
 8   loudness            5399 non-null   float64
 9   mode                5399 non-null   int64  
 10  speechiness         5399 non-null   float64
 11  acousticness        5399 non-null   float64
 12  instrumentalness    5399 non-null   float64
 13  liveness            5399 non-null   float64
 14  valence             5399 non-null   float64
 15  tempo               5399 non-null   float64
 16  durati

In [4]:
trainDS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12597 entries, 0 to 12596
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0.1        12597 non-null  int64  
 1   Unnamed: 0          12597 non-null  int64  
 2   Artist Name         12597 non-null  object 
 3   Track Name          12597 non-null  object 
 4   Popularity          12597 non-null  float64
 5   danceability        12597 non-null  float64
 6   energy              12597 non-null  float64
 7   key                 12597 non-null  float64
 8   loudness            12597 non-null  float64
 9   mode                12597 non-null  int64  
 10  speechiness         12597 non-null  float64
 11  acousticness        12597 non-null  float64
 12  instrumentalness    12597 non-null  float64
 13  liveness            12597 non-null  float64
 14  valence             12597 non-null  float64
 15  tempo               12597 non-null  float64
 16  dura

Converting the class to string:

In [5]:

testDS.Class = testDS.Class.astype(str)
trainDS.Class = trainDS.Class.astype(str)

In [6]:
trainDS.head()

Unnamed: 0.1  Unnamed: 0    Artist Name          Track Name  Popularity  \
0          7953        7953  Rodney Atkins        Watching You        68.0   
1         11302       11302        Defocus             Diverge        32.0   
2         17034       17034  Pablo Briceño  Preludio del valle        43.0   
3         17832       17832    Blind Melon             No Rain        75.0   
4          7468        7468         Tesher         Jalebi Baby        78.0   

   danceability  energy  key  loudness  mode  speechiness  acousticness  \
0         0.625   0.848  2.0    -4.008     1       0.0314      0.105000   
1         0.438   0.992  1.0    -3.754     1       0.1350      0.000103   
2         0.384   0.185  9.0   -14.269     0       0.0774      0.991000   
3         0.389   0.476  9.0    -9.342     1       0.0316      0.619000   
4         0.680   0.895  2.0    -7.144     1       0.0378      0.015600   

   instrumentalness  liveness  valence    tempo  duration_in min/ms  \
0          0.177562    0.2300    0.716  137.993            3.923783   
1          0.000002    0.4410    0.129  104.953       197040.000000   
2          0.844000    0.0931    0.150  149.834            2.526950   
3          0.000051    0.2550    0.566  148.117       217107.000000   
4          0.000374    0.1450    0.824   93.037            3.156250   

   time_signature Class  
0               4     4  
1               4     8  
2               3     7  
3               4     6  
4               4     9

In [7]:
testDS.head()

Unnamed: 0.1  Unnamed: 0  Artist Name  \
0         17738       17738    Los Coast   
1          9861        9861  Rendez Vous   
2          6295        6295   Tim Hardin   
3          9903        9903          iRO   
4         10746       10746  girl in red   

                                          Track Name  Popularity  \
0                             A Change Is Gonna Come        45.0   
1                                 Sentimental Animal        39.0   
2  How Can We Hang On to a Dream - Live at Woodst...        26.0   
3                                   Change Your Mind        36.0   
4                                          Serotonin        77.0   

   danceability  energy   key  loudness  mode  speechiness  acousticness  \
0         0.354   0.523  10.0    -5.938     1       0.0269      0.514000   
1         0.467   0.769   2.0    -5.059     1       0.0393      0.000039   
2         0.449   0.246   7.0   -14.743     0       0.0392      0.944000   
3         0.531   0.772   9.0    -4.126     1       0.0446      0.054100   
4         0.580   0.788   2.0    -4.714     1       0.2590      0.012300   

   instrumentalness  liveness  valence    tempo  duration_in min/ms  \
0          0.000027    0.1390    0.179  176.688            203616.0   
1          0.572000    0.3200    0.607  155.957            275391.0   
2          0.000240    0.4170    0.226  110.614            269000.0   
3          0.006930    0.0827    0.842  175.022            180273.0   
4          0.000018    0.3680    0.720  148.992            182426.0   

   time_signature Class  
0               3     2  
1               4     1  
2               3    10  
3               4     9  
4               4    10

In [8]:
# sns.boxenplot(data=DS,x="energy",y="key",hue="Class")

In [9]:
# sns.countplot(data=DS,x="key",hue="Class")

In [7]:

X_train = trainDS.iloc[:,-7:-3].values
y_train = trainDS.iloc[:,-1].values

print(X_train,y_train)

[[1.77561925e-01 2.30000000e-01 7.16000000e-01 1.37993000e+02]
 [2.36000000e-06 4.41000000e-01 1.29000000e-01 1.04953000e+02]
 [8.44000000e-01 9.31000000e-02 1.50000000e-01 1.49834000e+02]
 ...
 [1.77561925e-01 1.79000000e-01 3.12000000e-01 7.80350000e+01]
 [5.64000000e-04 3.73000000e-02 7.35000000e-01 1.01174000e+02]
 [8.25000000e-01 3.60000000e-02 5.93000000e-01 1.50307000e+02]] ['4' '8' '7' ... '5' '10' '6']


In [8]:
X_test = testDS.iloc[:,-7:-3].values
y_test = testDS.iloc[:,-1].values

print(X_test,y_test)

[[2.66000000e-05 1.39000000e-01 1.79000000e-01 1.76688000e+02]
 [5.72000000e-01 3.20000000e-01 6.07000000e-01 1.55957000e+02]
 [2.40000000e-04 4.17000000e-01 2.26000000e-01 1.10614000e+02]
 ...
 [1.77561925e-01 9.71000000e-02 5.65000000e-01 1.35986000e+02]
 [1.16000000e-05 1.05000000e-01 2.87000000e-01 1.55990000e+02]
 [2.55000000e-04 2.67000000e-01 2.91000000e-01 1.20044000e+02]] ['2' '1' '10' ... '9' '0' '10']


In [12]:

# spearmaner_cof, p_value = spearmanr(x,y)

# spearmaner_cof

In [13]:
# plt.scatter(x,y)

## preprocising

### test

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_test[:,2] = le.fit_transform(X_test[:,2])

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X_test = np.array(ct.fit_transform(X_test))

### Train

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train[:,2] = le.fit_transform(X_train[:,2])

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))

In [18]:
# x = testDS.Class
# # x.reshape(-1, 1)

# y = testDS.tempo
# # y.reshape(-1, 1)

In [19]:
# type(x)

In [20]:
# log_reg.fit(x,y)

In [21]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 123)


In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
from sklearn.linear_model import LogisticRegression



logistic_regression = LogisticRegression()
logistic_regression.fit(X_train,y_train)



In [ ]:
predictions = logistic_regression.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

In [ ]:


from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = logistic_regression.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

